version: "3"
services:
  mysql:
    image: mysql
    restart: always
    networks:
      - network-wvp
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./wvp/sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    restart: always
    networks:
      - network-wvp
    volumes:
      - redis-data:/data
    depends_on:
      - mysql

  zlm:
    #image: taoxin/zlm
    build:
      context: ./zlm
      args:
        ubuntuMirrorSite: "mirrors.aliyun.com"
        githubProxy: "http://10.66.66.4:3128/"
    restart: always
    networks:
      - network-wvp
    ports:
      - 8088:8088
      - 8089:8089
      - 1935:1935
      - 554:554
      - 554:554/udp
      - 10000:10000
      - 10000:10000/udp
      - 30000-30200:30000-30200
      - 30000-30200:30000-30200/udp
      - 8000:8000/udp
      - 9000:9000
    environment:
      - SERVERID=DefaultMediaServer
      - SECRET=035c73f7-bb6b-4889-a715-d9eb2d1925ee
      - PORT=8088
    depends_on:
      - redis

  wvp:
    # image: taoxin/wvp
    build:
      context: ./wvp
      args:
        ubuntuMirrorSite: "mirrors.aliyun.com"
        githubProxy: "http://10.66.66.4:3128/"

    restart: always
    networks:
      - network-wvp
    environment:
      - STREAM_IP=192.168.112.136 #流IP，外网
      - SDP_IP=192.168.112.136 #SDP协议IP，国标信令中使用的IP，此IP为摄像机可以访问到的IP，外网
      - HOOK_IP=wvp #zlm服务器访问wvp的IP
      - WVP_SHOW_IP=192.168.112.136  #对外显示IP，一般用外网
      - WVP_PORT=5060 #国标端口
      - WVP_DOMAIN=6202000049
      - WVP_ID=62020000492000000001
      - WVP_PWD=abcd1234
      - ZLM_ID=DefaultMediaServer #与zlm服务的'SERVERID'保持一致
      - ZLM_IP=zlm #zlm服务内网IP
      - ZLM_PORT=8088 #zlm服务http端口，与zlm服务的'PORT'保持一致
      - ZLM_SECRET=035c73f7-bb6b-4889-a715-d9eb2d1925ee #与zlm服务的'SECRET'保持一致
      - WVP_JVM_CONFIG=-Xms128m -Xmx256m
    ports:
      - 18080:18080
      - 5060:5060
      - 5060:5060/udp
    volumes:
      - ./wvp/application.yml:/opt/wvp/config/application.yml
    depends_on:
      - zlm

networks:
  network-wvp:

volumes:
  redis-data:
  mysql-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mysql-data-new'
